import type { Metadata } from "next";
import { CopilotKit } from "@copilotkit/react-core";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CopilotKit publicApiKey="ck_pub_ff8920cf96bfa51923dc4c4d2d56ef11" showDevConsole={false}>
          {children}
        </CopilotKit>
      </body>
    </html>
  );
}
